if(1){
clear;
clc;
clearfunctions;
switchtolayout;
deleteall;
}
Configure_Setup;

################################
# Basic Configure Once
################################
sim = init();
sim.L = um(3);
sim.route_wg_L = um(2);
sim.mesh_size = nm(50);
sim.ida = nm(785);
sim.mesh_acc = 4;
sim.movie = 0;
sim.pix   = 500;


w = um(4);
sim.w1 = w;
sim.w2 = w;

geo_config(sim);
sim_FDTD_config(sim);


################################
# Double Loop 
################################
ida_list   = [785];
width_list = um(1.5):um(0.5):um(8);  
N          = length(width_list);
N2         = length(ida_list);
d_set      = {
                "w450" : zeros(1, N),
                "w520" : zeros(1, N),
                "w633" : zeros(1, N),
                "w785" : zeros(1, N)
            };

for (j=1:N2){
    ida = ida_list(j);
    ida_string = num2str(ida);
    s21_list   = zeros(N);    
    print('Running '+ida_string); 
    sim.ida=nm(ida);
    
    for(i = 1:N) {
    ######################
    # Configure Change
    ######################
    switchtolayout;
    deleteall;
    w = width_list(i);
    sim.w1 = w;
    sim.w2 = w;
    geo_config(sim);        
    sim_FDTD_config(sim); 
    run;
    
    ######################
    # Read Result
    ######################
    temp = getresult("ModeExpand_x2", "expansion for Power_x2");
    T2 = temp.T_forward;
    freq = getdata("Power_x2", "f");
    wl = c / freq * 1e9;
    T_ida = interp(T2, wl, sim.ida * 1e9);
    T_avg = mean(T2);
    
    s21_list(i) = T_ida;
    print("Width = " + num2str(w / um(1)) + " µm, T(ida) = " + num2str(T_ida) + ", Avg = " + num2str(T_avg));
    }
    
    if (ida == 450) { d_set.w450 = s21_list; }
    if (ida == 520) { d_set.w520 = s21_list; }
    if (ida == 633) { d_set.w633 = s21_list; }
    if (ida == 785) { d_set.w785 = s21_list; }
}
##
## Single Shot
try{
matlabput(width_list, s21_list);
matlab("
    fs = 18;
    ms = 8;
    fig = figure;
    set(fig, 'Position', [300, 400, 700, 500]);
    plot(width_list * 1e6, s21_list, '-o', ...
        'LineWidth', 2, 'MarkerSize', ms, ...
        'DisplayName', '|S_{21}|^2', 'Color', 'b');
    grid on;
    xlabel('Waveguide Width (\\mum)', 'FontSize', fs);
    ylabel('Coupling Efficiency |S_{21}|^2', 'FontSize',fs);
    title('Width Sweep Result', 'FontSize', fs);
    set(gca, 'FontSize', fs);
    legend('Location', 'best', 'FontSize', fs);
");
}